name: TTSVibeLounge
on:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container: alexlaverty/ttsvibelounge:1.0.3
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout repo content to github runner.

      - name: Run ttsvibelounge Script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CREDENTIALS_STORAGE: ${{ secrets.CREDENTIALS_STORAGE }}
          PRAW_CLIENT_ID: ${{ secrets.PRAW_CLIENT_ID }}
          PRAW_CLIENT_SECRET: ${{ secrets.PRAW_CLIENT_SECRET }}
          PRAW_USER_AGENT: ${{ secrets.PRAW_USER_AGENT }}
          RUMBLE_PASSWORD: ${{ secrets.RUMBLE_PASSWORD }}
          RUMBLE_USERNAME: ${{ secrets.RUMBLE_USERNAME }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
        run: |
          echo $YOUTUBE_CLIENT_SECRET > client_secret.json
          echo $CREDENTIALS_STORAGE > credentials.storage
          cp config/auth-env.py config/auth.py
          #playwright install
          # python3 app.py --total-posts 1 \
          #                --enable-upload \
          #                --enable-background \
          #                --background-directory /app/assets/backgrounds
          echo "Hello" > data.csv
          rm -f client_secret.json
          rm -f credentials.storage
          git config --global --add safe.directory '*'
          git status
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.csv
          cat data.csv
          git commit -m "TTSVibeLounge Scheduled Update" -a
          git push -f
