name: TTSVibeLounge
on:
  schedule:
    - cron: '0 */6 * * *'
#   push:
#     branches:
#       - main
jobs:
  build:
    runs-on: ubuntu-latest
    container: alexlaverty/ttsvibelounge:1.0.6
    steps:

      # # Git version in container must match git version on ubuntu server
      # - name: get git
      #   run: |
      #     apt update -y
      #     apt install -y libz-dev libssl-dev libcurl4-gnutls-dev libexpat1-dev gettext cmake gcc
      #     wget https://github.com/git/git/archive/refs/tags/v2.38.1.tar.gz
      #     tar -xvf v2.38.1.tar.gz
      #     cd git-2.38.1
      #     make prefix=/usr/local all
      #     make prefix=/usr/local install
      #     git --version
      #     gh secret set CREDENTIALS_STORAGE_REFRESH < credentials.storage

      - name: checkout repo content
        uses: actions/checkout@v3

      - name: Run ttsvibelounge Script
        env:
          RYBO_POLLY_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          RYBO_POLLY_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CREDENTIALS_STORAGE: ${{ secrets.CREDENTIALS_STORAGE }}
          RYBO_REDDIT_CLIENT_ID: ${{ secrets.PRAW_CLIENT_ID }}
          RYBO_REDDIT_CLIENT_SECRET: ${{ secrets.PRAW_CLIENT_SECRET }}
          RYBO_REDDIT_USER_AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0
          RYBO_REDDIT_USERNAME: ${{ secrets.PRAW_USERNAME }}
          RYBO_REDDIT_PASSWORD: ${{ secrets.PRAW_PASSWORD }}
          RYBO_RUMBLE_PASSWORD: ${{ secrets.RUMBLE_PASSWORD }}
          RYBO_RUMBLE_USERNAME: ${{ secrets.RUMBLE_USERNAME }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo $PWD
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
          echo $YOUTUBE_CLIENT_SECRET > client_secret.json
          echo $CREDENTIALS_STORAGE > credentials.storage
          pip install -r requirements.txt
          playwright install
          pip install --editable .
          rybo --total-posts 1 \
               --enable-upload \
               --enable-background \
               --background-directory /app/assets/backgrounds \
               --enable-mentions
          python3 refresh_token.py
          rm -f client_secret.json
          rm -f credentials.storage

      - name: check for changes
        run: |
          git config --global --add safe.directory $(realpath .)
          if git diff --exit-code data.csv; then
             echo changes_exist=false
            echo "changes_exist=false" >> $GITHUB_ENV
          else
            echo changes_exist=true
            echo "changes_exist=true" >> $GITHUB_ENV
          fi

      - name: Push updates
        if: env.changes_exist == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.csv
          git commit -m "TTSVibeLounge Scheduled Update" -a
          git push -f
