# Give your gitflow action a name
name: TTSVibeLounge

# Set a schedule to run, note it's in UTC time, so do the time conversion for your location
on:
  schedule:
    - cron: '0 0 * * *'

# Also run the build if I push anything into the master branch
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container: alexlaverty/ttsvibelounge:1.0.0
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.

      - name: Run ttsvibelounge Script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CREDENTIALS_STORAGE: ${{ secrets.CREDENTIALS_STORAGE }}
          PRAW_CLIENT_ID: ${{ secrets.PRAW_CLIENT_ID }}
          PRAW_CLIENT_SECRET: ${{ secrets.PRAW_CLIENT_SECRET }}
          PRAW_USER_AGENT: ${{ secrets.PRAW_USER_AGENT }}
          RUMBLE_PASSWORD: ${{ secrets.RUMBLE_PASSWORD }}
          RUMBLE_USERNAME: ${{ secrets.RUMBLE_USERNAME }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
        run: |
          echo $YOUTUBE_CLIENT_SECRET > client_secret.json
          echo $CREDENTIALS_STORAGE > credentials.storage
          cp config/auth-env.py config/auth.py
          playwright install
          python3 app.py --enable-upload
          rm -f client_secret.json
          rm -f credentials.storage
